<a href="https://colab.research.google.com/github/vikramvundyala/python_AI-ML/blob/main/U1_MH1_Data_Munging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

## Learning Objective

At the end of this experiment, you will be able to:

* perform Data preprocessing

In [ ]:
#@title  Mini Hackathon Walkthrough
from IPython.display import HTML

HTML("""<video width="640" height="420" controls>
  <source src="https://cdn.talentsprint.com/talentsprint/archives/sc/aiml/aiml_batch_15/preview_videos/Mini_Hackathon_Data_Munging_Briefing.mp4" type="video/mp4">
</video>
""")

## Problem Statement

We will be using district wise demographics, enrollments, and teacher indicator data to predict whether the literacy rate is high/ medium/ low in each district.

### Data Preprocessing

Data preprocessing is an important step in solving every machine learning problem. Most of
the datasets used with Machine Learning problems need to be processed / cleaned / transformed
so that a Machine Learning algorithm can be trained on it.

There are different steps involved in Data Preprocessing. These steps are as follows:

    1. Data Cleaning → In this step the primary focus is on
        - Handling missing data
        - Handling noisy data
        - Detection and removal of outliers
    
    2. Data Integration → This process is used when data is gathered from various data sources and data are combined to form consistent data.
    This data after performing cleaning is used for analysis.
    
    3. Data Transformation → In this step we will convert the raw data into a specified format according to the need of the model we are building.
    There are many options used for transforming the data as below:
        - Normalization
        - Aggregation
        - Generalization
        
    4. Data Reduction → Following data transformation and scaling, the redundancy within the data is removed and is organized efficiently.

### Total Marks  = 20

In [1]:
# @title Download the datasets
from IPython import get_ipython

ipython = get_ipython()

notebook="U1_MH1_Data_Munging" #name of the notebook

def setup():
    from IPython.display import HTML, display
    ipython.magic("sx wget https://cdn.iiith.talentsprint.com/aiml/Experiment_related_data/B15_Data_Munging.zip")
    ipython.magic("sx unzip B15_Data_Munging.zip")
    print("Data downloaded successfully")
    return

setup()

Data downloaded successfully

In [2]:
!ls

B15_Data_Munging.zip
Districtwise_Basicdata.csv
Districtwise_Enrollment_details_indicator.csv
Districtwise_Teacher_indicator.csv
sample_data

## Exercise 1 - Load and Explore the Data (3 Marks)
1. We have three different files

  * Districtwise_Basicdata.csv
  * Districtwise_Enrollment_details_indicator.csv
  * Districtwise_Teacher_indicator.csv

  These files contain the necessary data to solve the problem. <br>

2. Load the files based on **team allocation** mentioned below. Observe the header level details, data records while loading the data.
  
  Hint : Use read_csv from pandas with [skiprows or header](https://towardsdatascience.com/import-csv-files-as-pandas-dataframe-with-skiprows-skipfooter-usecols-index-col-and-header-fbf67a2f92a) options.

3. Read the columns of the dataset and rename them if required.

  Hint : Rename column names (if any) using the following [link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html).

Team allocation for dataset selection

    Team A = 1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33
        Districtwise_Basicdata.csv
        Districtwise_Enrollment_details_indicator.csv

    Team B = 2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32
        Districtwise_Basicdata.csv
        Districtwise_Teacher_indicator.csv

In [14]:
# Importing all the required packages and add necessary imports if required
import pandas as pd
import numpy as np

In [108]:
# YOUR CODE HERE for loading and exploring the datasets

dwBasicDataset = pd.read_csv("Districtwise_Basicdata.csv",skiprows=1)
dwEnrollmentDataset = pd.read_csv("Districtwise_Enrollment_details_indicator.csv",skiprows=3)
dwTeacherDataset = pd.read_csv("Districtwise_Teacher_indicator.csv",skiprows=3)

dwTeacherDataset.rename(columns={'ac_year': 'Year'}, inplace=True)

dwBasicDataset.columns = dwBasicDataset.columns.str.strip().str.lower().str.replace(' ', '_')
dwEnrollmentDataset.columns = dwEnrollmentDataset.columns.str.strip().str.lower().str.replace(' ', '_')
dwTeacherDataset.columns = dwTeacherDataset.columns.str.strip().str.lower().str.replace(' ', '_')

## Exercise 2  - Data Integration (3 Marks)

As the required data is present in different datasets, we need to **integrate both to make a single dataframe/dataset**.
  * For integrating the datasets, create a unique identifier for each row in both the dataframes so that it can be used to map the data in different files.
   
    * Combine year, state code, district code columns and form a new unique identifier column, refer to this [link](https://stackoverflow.com/questions/33098383/merge-multiple-column-values-into-one-column-in-python-pandas).
    * Set the identifier column as the index for each dataframe.

    * Integrate the dataframes using the above index
     
     Hint: For merging or joining the datasets, refer to this [link](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html)

**Example:** Data of the district Anantapur in Andrapradesh, which is present in different files should form a single row after integrating the datasets

In [109]:
# YOUR CODE HERE for integrating the datasets


dwBasicDataset["unique_id"] = dwBasicDataset["year"].astype(str) + '-' + dwBasicDataset["statecd"].astype(str) + '-' + dwBasicDataset["distcd"].astype(str)
dwEnrollmentDataset["unique_id"] = dwEnrollmentDataset["year"].astype(str) + '-' + dwEnrollmentDataset["statecd"].astype(str) + '-' + dwEnrollmentDataset["distcd"].astype(str)
dwTeacherDataset["unique_id"] = dwTeacherDataset["year"].astype(str) + '-' + dwTeacherDataset["statecd"].astype(str) + '-' + dwTeacherDataset["distcd"].astype(str)

dwBasicDataset.set_index("unique_id",inplace=True)
dwEnrollmentDataset.set_index("unique_id",inplace=True)
dwTeacherDataset.set_index("unique_id",inplace=True)

dwEnrollmentDataset.drop(columns=[col for col in dwEnrollmentDataset.columns if col in dwBasicDataset.columns],inplace=True)
dwTeacherDataset.drop(columns=[col for col in dwTeacherDataset.columns if col in dwBasicDataset.columns],inplace=True)

df = pd.merge(dwBasicDataset,dwEnrollmentDataset,on="unique_id")
df = pd.merge(df,dwTeacherDataset,on="unique_id")

In [110]:
print(df.columns)
print(df.shape)

Index(['year', 'statecd', 'statename', 'distcd', 'distname', 'blocks',
       'clusters', 'villages', 'totschools', 'totpopulation',
       ...
       'trn_tch_f2', 'trn_tch_f3', 'trn_tch_f4', 'trn_tch_f5', 'trn_tch_f6',
       'trn_tch_f7', 'prof_trn_tch_r', 'prof_trn_tch_p', 'days_nontch',
       'tch_nontch'],
      dtype='object', length=357)
(1324, 357)

## Exercise 3 - Data Cleaning (3 Marks)

1.  **Overall_lit** is our target variable. Delete rows with missing overall_lit value

   Hint: Refer to the link [dropna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html).


2.  Convert categorical values to numerical values.

  For example, If a feature contains categorical values such as dog, cat, mouse, etc then replace them with 0, 1, 2, etc or use [Sklearn LabelEncoder's](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html)

3. Replace the missing values in any other column appropriately with mean / median / mode.

  Hint: Use pandas [fillna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html) function to replace the missing values

In [111]:
# YOUR CODE HERE for data cleaning
df['overall_lit'].isna().sum()

df.dropna(subset=['overall_lit'],inplace=True)


df['overall_lit'].isna().sum()
df.shape
df.head()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['statename'] = le.fit_transform(df['statename'])
df['distname'] = le.fit_transform(df['distname'])
df['overall_lit'] = le.fit_transform(df['overall_lit'])
df['year'] = le.fit_transform(df['year'])

df.head()

print(df.dtypes)

for col in df.select_dtypes(include='Int64'):
    df[col] = df[col].fillna(df[col].median())


# df.fillna(df.mean(),inplace=True)
# df.head()

year              int64
statecd           int64
statename         int64
distcd            int64
distname          int64
                  ...
trn_tch_f7        int64
prof_trn_tch_r    int64
prof_trn_tch_p    int64
days_nontch       int64
tch_nontch        int64
Length: 357, dtype: object

## Exercise 4 - (3 Marks)

1. Remove the unnecessary columns which are not contributing to the overall literacy rate

2. Verify if there are any duplicate columns and remove them.

  For example: state name and district name are the same as state code and district code.

3. Make sure that the final dataframe has no null or nan values. Delete the rows with missing values.

   Hint: Give df.isna() to verify on the nan values in the dataframe.

In [112]:
# YOUR CODE HERE for cleaning the dataframe
df.drop_duplicates(inplace=True)

df = df.drop(columns=['statename', 'state_name', 'distname'], axis=1)
df_cleaned = df.dropna(axis=1)

In [99]:
df.head()
df.dtypes

year              int64
statecd           int64
distcd            int64
blocks            int64
clusters          int64
                  ...
trn_tch_f7        int64
prof_trn_tch_r    int64
prof_trn_tch_p    int64
days_nontch       int64
tch_nontch        int64
Length: 318, dtype: object

In [113]:
object_cols = df_cleaned.select_dtypes(include='object').columns
print(object_cols)

Index([], dtype='object')

## Exercise 5 - Apply Correlation Matrix (2 Marks)

Correlation is a statistical technique that can show whether and how strongly pairs of variables are related. More number of features does not imply better accuracy. More features may lead to a decline in the accuracy and create noise in the model, if they contain any irrelevant features.

*Features with high correlation value will imply the same meaning. Hence removing the highly correlated features*

**Function Description:**

`remove_Highly_Correlated()` function removes highly correlated features in the dataframe.
- Creates a correlation matrix of row and column wise features
- Extracts only uppertriangular matrix as correlation matrix, which will have the same values below and above the diagonal
- Removes columns which are having correlation value more than the threshold value.

In [114]:
def remove_Highly_Correlated(df, bar=0.9):
  # Creates correlation matrix
  corr = df.corr()

  # Set Up Mask To Hide Upper Triangle
  mask = np.triu(np.ones_like(corr, dtype=bool))
  tri_df = corr.mask(mask)

  # Finding features with correlation value more than specified threshold value (bar=0.9)
  highly_cor_col = [col for col in tri_df.columns if any(tri_df[col] > bar )]
  print("length of highly correlated columns",len(highly_cor_col))

  # Drop the highly correlated columns
  reduced_df = df.drop(highly_cor_col, axis = 1)
  print("shape of data",df.shape,"shape of reduced data",reduced_df.shape)
  return reduced_df

In [115]:
# YOUR CODE HERE to remove highly correlated features from the dataframe by calling above function.
df_corr = remove_Highly_Correlated(df_cleaned)

length of highly correlated columns 113
shape of data (1268, 317) shape of reduced data (1268, 204)

In [116]:
df_corr.head()

,year,distcd,blocks,clusters,villages,totschools,sexratio,growthrate,overall_lit,female_lit,...,trn_tch_f2,trn_tch_f3,trn_tch_f4,trn_tch_f5,trn_tch_f6,trn_tch_f7,prof_trn_tch_r,prof_trn_tch_p,days_nontch,tch_nontch
unique_id,,,,,,,,,,,,,,,,,,,,,
2012-13-35-3501,0,3501,3,16,83,212,874.0,13.97,0,84.52,...,176,135,0,22,103,0,2968,228,12,519
2012-13-35-3503,0,3503,3,13,76,181,925.0,-0.07,0,79.39,...,85,40,3,28,60,0,1249,203,8,362
2012-13-35-3502,0,3502,3,8,42,58,778.0,-12.48,0,70.70,...,29,23,0,17,46,0,430,78,20,28
2012-13-28-2801,0,2801,52,356,1576,4983,1003.0,10.04,1,51.99,...,267,0,0,0,8,248,16419,845,13,263
2012-13-28-2822,0,2822,63,564,929,5188,977.0,12.16,1,54.31,...,726,0,0,591,0,3,21487,676,14,1185

## Exercise 6 - (3 Marks)

Perform Standard Scaling on the data feature/column wise.

**Hint:** In order to understand the idea behind the terms used above, you may refer to the following link:

[StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html)

In [117]:
# YOUR CODE HERE
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df_corr),columns=df_corr.columns)
df_scaled.head()

,year,distcd,blocks,clusters,villages,totschools,sexratio,growthrate,overall_lit,female_lit,...,trn_tch_f2,trn_tch_f3,trn_tch_f4,trn_tch_f5,trn_tch_f6,trn_tch_f7,prof_trn_tch_r,prof_trn_tch_p,days_nontch,tch_nontch
0,-1.0,1.894217,-0.828445,-1.109180,-1.307226,-1.375512,-1.101203,-0.322648,-1.062757,1.592947,...,-0.292820,0.514248,-0.494098,-0.292423,1.274906,-0.377127,-0.785267,-0.293687,-0.359209,0.047086
1,-1.0,1.896343,-0.828445,-1.138707,-1.318262,-1.396885,-0.283457,-1.561064,-1.062757,1.182316,...,-0.395004,0.038853,-0.470878,-0.264741,0.625907,-0.377127,-1.026722,-0.329009,-0.618519,-0.089579
2,-1.0,1.895280,-0.828445,-1.187918,-1.371868,-1.481690,-2.640491,-2.655703,-1.062757,0.486725,...,-0.457886,-0.046217,-0.494098,-0.315492,0.414605,-0.377127,-1.141760,-0.505620,0.159410,-0.380319
3,-1.0,1.149962,4.173296,2.237191,1.046709,1.913955,0.967214,-0.669299,0.062098,-1.010916,...,-0.190636,-0.161313,-0.494098,-0.393926,-0.158929,1.903111,1.104093,0.578065,-0.294382,-0.175757
4,-1.0,1.172289,5.296136,4.284383,0.026618,2.055296,0.550323,-0.482302,0.062098,-0.825212,...,0.324775,-0.161313,-0.494098,2.332798,-0.279673,-0.349544,1.815956,0.339287,-0.229554,0.626826

## Exercise 7 - (3 Marks)

Apply different classifiers on the preprocessed data and figure out which classifier gives the best result.

* Split the data into train and test

* Fit the model with train data and find the accuracy of test data

### Expected Accuracy is above 90%

In [135]:
# YOUR CODE HERE for applying different classifiers
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

features_data = df_scaled.drop('overall_lit', axis=1)
target_data = df_scaled['overall_lit']
target_data = le.fit_transform(target_data)

X_train, X_test, y_train, y_test = train_test_split(features_data, target_data, test_size= 0.2, random_state=42)


model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy_lc = accuracy_score(y_test, y_pred)
print("Accuracy_LC:", accuracy_lc)

dt = DecisionTreeClassifier(max_depth=5)
dt.fit(X_train, y_train)

y_pred = dt.predict(X_test)

accuracy_dt = accuracy_score(y_test, y_pred)
print("Accuracy_DT:", accuracy_dt)


knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

accuracy_knn = accuracy_score(y_test, y_pred)
print("Accuracy_KNN:", accuracy_knn)

Accuracy_LC: 0.8582677165354331
Accuracy_DT: 0.9173228346456693
Accuracy_KNN: 0.7244094488188977